name: IP Address Counter CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name/Purpose for the run'
        required: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build the Project
      run: ./mvnw clean install
